spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidsart
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215KB


upload:
    path: /home/zeecoder/owner/dev/homeprojects/kidsart/src/main/resources/static/img



