spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidsart
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    show-sql: true






