spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidsart
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres1
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    show-sql: true



  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 837199908933-92pjhc4e1r3dfsgn1bri62aa0js32khp.apps.googleusercontent.com
            clientSecret: 2GOvEKVsKjVFkHlrfCESEw9Y



